<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

1. Compute the scaler product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. 

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [2]:
import numpy as np

In [13]:
a = [-12, 16]
b = [12, 9]

dot_product = a[0]*b[0] + a[1]*b[1]
print(dot_product)
print(dot_product == np.dot(a,b))

0
True


2. Compute the cross product of two vectors

> When a and b start at the origin point (0,0,0), the Cross Product will end at:

        cx = aybz − azby
        cy = azbx − axbz
        cz = axby − aybx
        
Hint: [Cross Product](https://www.mathsisfun.com/algebra/vectors-cross-product.html)

In [14]:
#############  x y z   x  y z
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[4,5,6], [1,2,3]])

def cross_prod(ndarray):
    
    cross_prod_x = ndarray[0][1]*ndarray[1][2] - ndarray[0][2]*ndarray[1][1]
    cross_prod_y = ndarray[0][2]*ndarray[1][0] - ndarray[0][0]*ndarray[1][2]
    cross_prod_z = ndarray[0][0]*ndarray[1][1] - ndarray[0][1]*ndarray[1][0]
    
    return cross_prod_x,cross_prod_y,cross_prod_z

print(cross_prod(a),cross_prod(b))
print(np.cross(a[0],a[1]),np.cross(b[0],b[1]))

(-3, 6, -3) (3, -6, 3)
[-3  6 -3] [ 3 -6  3]


3. Compute the Hademard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [16]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

hademard_prod = [[a[0][0]*b[0][0],a[0][1]*b[0][1]],
                 [a[1][0]*b[1][0],a[1][1]*b[1][1]]]

print(hademard_prod)
print(np.multiply(a,b))

[[5, 12], [21, 32]]
[[ 5 12]
 [21 32]]


4. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [44]:
# Program to add two matrices using nested loop

matrix_x = [[12,7,3],
            [4 ,5,6],
            [7 ,8,9]]

matrix_y = [[5,8,1],
            [6,7,3],
            [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(matrix_x)):
    for j in range(len(matrix_x[0])):
        result[i][j] = matrix_x[i][j] + matrix_y[i][j]
        
result

[[17, 15, 4], [10, 12, 9], [11, 13, 18]]

5. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [3]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
matrix_a = [[12,7,3],
            [4 ,5,6],
            [7 ,8,9]]

# 3x4 matrix
matrix_b = [[5,8,1,2],
            [6,7,3,0],
            [4,5,9,1]]

# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

for y in range(len(matrix_a)):
    for x in range(len(matrix_b[0])):
        for z in range(len(matrix_a[0])):
            result[y][x] = result[y][x] + matrix_a[y][z]*matrix_b[z][x]
            
        #result[y][x] = matrix_a[y][0]*matrix_b[0][x] + matrix_a[y][1]*matrix_b[1][x] + matrix_a[y][2]*matrix_b[2][x]
        
print(result)
np.matmul(matrix_a,matrix_b)

[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]


array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

6. Compute the determinant of an n x n matrix.

![](https://integratedmlai.com/wp-content/uploads/2018/12/Matrix_Det_2x2.png)

Hint: [Find the Determinant of a Matrix with Pure Python without Numpy or Scipy](https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/)

Hint: Use 
> np.linalg.det

In [51]:
matrix = [[-2,2,-3],
          [-1,1,3],
          [2,0,-1]]

# a11 = matrix[0][0]
# a12 = matrix[0][1]
# a13 = matrix[0][2]

# matrix_a11 = [matrix[1][1:],matrix[2][1:]]
# matrix_a12 = [[matrix[1][0],matrix[1][2]],[matrix[2][0],matrix[2][2]]]
# matrix_a13 = [matrix[1][:2],matrix[2][:2]]

# def calc_det_matrix(matrix,det):
    
#     return (det * (matrix[0][0]*matrix[1][1] - matrix[1][0]*matrix[0][1]))

# term_a11 = calc_det_matrix(matrix_a11,a11)
# term_a12 = calc_det_matrix(matrix_a12,a12)
# term_a13 = calc_det_matrix(matrix_a13,a13)

# ans = term_a11 - term_a12 + term_a13

# print(ans,np.linalg.det(matrix))

def determinant_recursive(A, total=0):
    # Section 1: store indices in list for row referencing
    indices = list(range(len(A)))
     
    # Section 2: when at 2x2 submatrices recursive calls end
    if len(A) == 2 and len(A[0]) == 2:
        val = A[0][0] * A[1][1] - A[1][0] * A[0][1]
        return val
 
    # Section 3: define submatrix for focus column and 
    #      call this function
    for fc in indices: # A) for each focus column, ...
        # find the submatrix ...
        As = A # B) make a copy, and ...
        As = As[1:] # ... C) remove the first row
        height = len(As) # D) 
 
        for i in range(height): 
            # E) for each remaining row of submatrix ...
            #     remove the focus column elements
            As[i] = As[i][0:fc] + As[i][fc+1:] 

        sign = (-1) ** (fc % 2) # F) 
        # G) pass submatrix recursively
        sub_det = determinant_recursive(As)
        # H) total all returns from recursion
        total += sign * A[0][fc] * sub_det 
 
    return total

determinant_recursive(matrix)

18

7. Compute the inverse of an n x n matrix.

For a 3×3 matrix

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation3.gif)

the matrix inverse is

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation4.gif)

Hint: Use 
> from numpy.linalg import inv

In [42]:
a = np.array([[1., 2.], 
              [3., 4.]])

det_a = a[0][0]*a[1][1] - a[0][1]*a[1][0]

det_inv_a = 1 / det_a

adj_a = [[a[1][1],-a[0][1]],
        [-a[1][0],a[0][0]]]

adj_a = np.array(adj_a)

inv_a = det_inv_a * adj_a

print(inv_a)

np.linalg.inv(a)

[[-2.   1. ]
 [ 1.5 -0.5]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])



---



---



> > > > > > > > > © 2021 Institute of Data


---



---



